[package]
name = "aes-256-gcm"
version = "0.1.0"
edition = "2021"

[lib]
name = "aes_256_gcm"
crate-type = ["cdylib", "staticlib"]

[dependencies]
aes-gcm = "0.11.0-rc.0"
hex = "0.4"

[features]
default = []